#spring:
#  rabbitmq:
#    host: 176.16.20.250   #rabbitMQ服务器地址
#    port: 5672            #rabbitMQ服务器端口
#    username: springcloud
#    password: 123456
#    virtual-host: springCloud

server:
  port: 9001
