spring:
  cloud:
    stream:
      bindings:
        worksChannel:                   #channelName
          destination: work.exchange    #destination，或者可以认为是发布－订阅模型里面的topic，这里应该与输出app中发布的topic一致，表示订阅该主题
          group: testgroup2             #组名，如果多个服务注册到同一个组内，则消息会使用负载均衡到每个消费者；分不同的组，消息会复制到每个组
          binder: rabbitmq1
      binders:
        rabbitmq1:
          type: rabbit                  #可以是其它，比如kafka
          environment:
            spring:
              rabbitmq:
                host: 172.16.20.250      #rabbitMQ服务器地址
                port: 5672              #rabbitMQ服务器端口
                username: springstream
                password: 123456
                virtual-host: springstream

server:
  port: 8003