server:
  port: 1113
spring:
  application:
    name: eureka-server
#  profiles: peer3
eureka:
  instance:
    hostname: eureka-peer3
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer1:1111/eureka/,http://eureka-peer2:1112/eureka/