server:
  port: 8001

spring:
  application:
    name: compute-service-dev
  cloud: #客户端服务启动时才会向配置中心请求配置文件，之后默认不会主动刷新
    config:
      uri: http://localhost:8888  #配置中心服务器地址,默认地址是8888
      name: cm  #定位gitHub资源，必须和配置中心的服务名称相同
      profile: dev #定位gitHub资源，必须和配置中心中的配置文件相同
      discovery:
        enabled: true #开启通过服务来访问Config Server的功能
        service-id: config-server #来指定Config Server注册的服务名


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/  #注册到eureka

