server:
  port: 1112
spring:
  application:
    name: eureka-server
#  profiles: peer2 #配置文件
eureka:
  instance:
    hostname: eureka-peer2
#    prefer-ip-address: true #实例名称显示IP配置
#    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer1:1111/eureka/