server:
  port: 1111


spring:
  application:
    name: eureka-server   #集群名称
    #profiles: peer1  #配置文件

eureka:
  instance:
    #metadataMap:
      #eureka instance标识，需要唯一，如果不配置，多个节点最终只会有一个生效
      #instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: eureka-peer1
#    prefer-ip-address: true #实例名称显示IP配置
    #instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-peer2:1112/eureka/  #相互注册即可构建高可用
#      defaultZone: http://localhost:${server.port}/eureka/ #自己注册自己即是单个服务器
